/**
 * WP0.2 — emit the UX-config SEED BODY from GARDEN_DEFAULT.
 *
 * Post-D1 there is NO global `sophia-ux` graph; workspace config lives per-cell
 * and the hand-maintained `GARDEN_DEFAULT` TS literal is the canonical source.
 * The old "regenerate garden-default.ts FROM the sophia-ux graph" job is dead.
 *
 * This generator runs the OPPOSITE direction: it serializes GARDEN_DEFAULT to the
 * deterministic N-Triples SEED BODY (via the WP0.1 contract
 * serializeConfigToTriples → triplesToNT) and writes it to a committed artifact.
 * That body is exactly what the gateway seed / WP5.1 / the Rust `ux_seed.rs`
 * (`build_ux_config_seed`) insert into a cell's `:ux:config` named graph. So the
 * build-time literal and the server seed are PROVABLY one source.
 *
 * It also asserts the WP0.1 round-trip (serialize → parse → deepEqual
 * GARDEN_DEFAULT) and exits non-zero on mismatch, so the artifact can never
 * silently drift from GARDEN_DEFAULT. Output is deterministic (the serializer
 * sorts every triple), so two runs are byte-identical — the git diff on the
 * artifact is empty unless GARDEN_DEFAULT actually changed.
 *
 * Run:  pnpm generate:ux-seed   (== pnpm exec tsx scripts/generate-garden-default.mts)
 */
import { createHash } from 'node:crypto'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { GARDEN_DEFAULT } from '../src/workspace/garden-default.js'
import {
  parseTriplesToConfig,
  serializeConfigToTriples,
  triplesToNT,
} from '../src/workspace/ux-rdf.js'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, '../src/workspace/__generated__')
const outPath = join(outDir, 'garden-default.ux.nt')

// 1. Serialize GARDEN_DEFAULT → deterministic, sorted Triple[] → N-Triples body.
const triples = serializeConfigToTriples(GARDEN_DEFAULT)
const body = triplesToNT(triples)

// 2. Round-trip guard: the artifact MUST be a faithful encoding of the literal.
//    serialize → parse → deepEqual GARDEN_DEFAULT (modulo freeze). Fail loudly so
//    the committed seed can never drift from the canonical source.
const back = parseTriplesToConfig(triples)
function deepEqual(a: unknown, b: unknown): boolean {
  return JSON.stringify(canonical(a)) === JSON.stringify(canonical(b))
}
// Stable key ordering so the deepEqual is order-insensitive over object keys.
function canonical(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(canonical)
  if (v && typeof v === 'object') {
    const o = v as Record<string, unknown>
    return Object.fromEntries(
      Object.keys(o)
        .sort()
        .map((k) => [k, canonical(o[k])]),
    )
  }
  return v
}
if (!deepEqual(back, GARDEN_DEFAULT)) {
  console.error(
    'WP0.2 FAILED: serialize → parse did NOT round-trip GARDEN_DEFAULT.\n' +
      'The ux-rdf contract and GARDEN_DEFAULT have drifted — refusing to write the seed.',
  )
  process.exit(1)
}

// 3. Write the committed artifact (trailing newline; one statement per line).
const sha = createHash('sha256').update(body).digest('hex')
const header = [
  '# GENERATED by scripts/generate-garden-default.mts — do not hand-edit.',
  '# UX-config seed body for GARDEN_DEFAULT (WP0.1 sux: schema).',
  '# This is the N-Triples body the gateway seed / WP5.1 / Rust ux_seed.rs',
  '# (build_ux_config_seed) insert into a cell\'s :ux:config named graph.',
  `# Triples: ${triples.length}   sha256(body): ${sha}`,
  '# Regenerate: pnpm generate:ux-seed',
].join('\n')
const contents = `${header}\n${body}\n`

mkdirSync(outDir, { recursive: true })
writeFileSync(outPath, contents)

console.log(`wrote UX-config seed body to ${outPath}`)
console.log(`triples: ${triples.length}, body bytes: ${body.length}, sha256: ${sha}`)
